### PR TITLE
string logging code sketch

### PR DESCRIPTION
**Pull request by wchristian**
This is a sketch for #7

### CODE REVIEW

**Comment by frioux** [comment]
Please also add tests

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Also seems like it'll do odd things if passed a false string?

-- 
sent from a rotary phone, pardon my brevity

**Comment by wchristian** [comment]
Added tests, including a failing test for pre-existing code, and fixed the handling of '' or '0'. Docs coming next.

**Comment by wchristian** [comment]
Alright, docs and code can be considered ready if you're ok with them. The question is what should happen with slog and slogS when given arguments. Right now they ignore them. An alternative i can think of is having them append them to the string with `$text . join " ", @args`.

Which of those do you prefer?

**Comment by frioux** [comment]
I think I prefer how it is now, but only because it's slightly simpler.

**Comment by wchristian** [comment]
Alright, then you can go ahead and pull, i think. :)

**Comment by frioux** [comment]
BTW your DlogS test is wrong; the S stands for scalar, and an empty list is not a scalar.  I'm probably going to just drop that test.  Also the code fails the tidy test but I'll just take care of that and ensure that in the future travis runs that automatically.

**Comment by wchristian** [comment]
Sure, thanks for the double-check. I must admit the tests had me getting into the woods a little. :)

As for tidy: Sorry, i'm not used to other people using it and didn't notice it when it scrolled past.

**Comment by frioux** [comment]
Merged, about to release.

**Pull request closed without merging**
